export const hashtags = [
  'Space Science',
  'abstract algebra',
  'accelerators',
  'accounting',
  'acoustics',
  'addication',
  'aerobiology',
  'aeronautics',
  'aerospace',
  'agriculture',
  'agrochemistry',
  'agronomy',
  'algebra',
  'algebraic geometry',
  'algebraic topology',
  'algorithms',
  'allergy',
  'analysis',
  'analysis of PDEs',
  'analytical chemistry',
  'analytics',
  'anatomy',
  'anesthesiology',
  'animation',
  'anova',
  'anthropology',
  'antibody',
  'applied chemistry',
  'applied mathematics',
  'applied optics',
  'applied physics',
  'applied probability',
  'applied statistics',
  'applied stochastic processes',
  'arachnology',
  'archaeology',
  'area studies',
  'arithmetic',
  'artificial intelligence',
  'arts',
  'astrobiology',
  'astrochemistry',
  'astrophysics',
  'astrostatistics',
  'asymptotic inference',
  'atmospheric chemistry',
  'atmospheric science',
  'atmospheric sciences',
  'atom optics',
  'atomic and molecular physics',
  'atomic clocks',
  'atomic physics',
  'audio',
  'autoimmunity',
  'automata theory',
  'automation',
  'automotive engineering',
  'autophagy',
  'aviation',
  'bacteria',
  'bacterial',
  'balloon and satellite measurements',
  'balloon experiments',
  'bayesian inference',
  'bell inequalities',
  'bifurcation theory',
  'biochemistry',
  'biodiversity',
  'bioengineering',
  'biogeography',
  'bioinformatics',
  'biomaterials',
  'biomechanics',
  'biomedical engineering',
  'biophotonics',
  'biophysics',
  'biosensors',
  'biostatistics',
  'biosynthesis',
  'biotechnology',
  'black holes',
  'botany',
  'brain disorders',
  'building biology',
  'building materials',
  'business',
  'business studies',
  'bussiness',
  'calculus',
  'cancer',
  'cancer metabolism',
  'cardiology',
  'cardiovascular diseases',
  'cardiovascular medicine',
  'cart',
  'catalysis',
  'category theory',
  'cavity qed',
  'cell biology',
  'cell fate',
  'cell signalling',
  'cellular automata',
  'chaotic dynamics',
  'chemical biology',
  'chemical engineering',
  'chemical physics',
  'chemo-informatics',
  'chemoinformatics',
  'chromatography',
  'circuits',
  'civil engineering',
  'classical analysis',
  'classical mechanics',
  'climate change',
  'climatology',
  'clinical genetics',
  'clinical immunology',
  'cloud computing',
  'cognitive neuroscience',
  'cognitive science',
  'coherent light sources',
  'collective behavior',
  'collective intelligence',
  'colloids',
  'colloids',
  'combinatorial chemistry',
  'combinatorics',
  'communication and control',
  'communication studies',
  'commutative algebra',
  'complex networks',
  'complex systems',
  'complex variables',
  'complexity theory',
  'computation and language',
  'computational biology',
  'computational chemistry',
  'computational complexity',
  'computational engineering',
  'computational finance',
  'computational geometry',
  'computational intelligence',
  'computational linguistics',
  'computational mathematics',
  'computational neuroscience',
  'computational physics',
  'computer architecture',
  'computer graphics',
  'computer simulations',
  'computer vision',
  'computing hardware',
  'condensed matter',
  'conservation biology',
  'control systems',
  'control theory',
  'cosmetic chemistry',
  'cosmic rays',
  'cosmochemistry',
  'cosmology',
  'criminology',
  'crisis management',
  'critical care medicine',
  'crowdsourcing',
  'cryobiology',
  'cryptography',
  'crystallography',
  'cultural and ethnic studies',
  'cybernetics',
  'dark matter',
  'darkenergy',
  'data analysis',
  'data management',
  'data mining',
  'data mining conference',
  'data structures and algorithms',
  'database',
  'databases',
  'dementia',
  'demography',
  'dentistry',
  'dermatology',
  'descriptive statistics',
  'development studies',
  'developmental biology',
  'devices and applications',
  'diabetes',
  'differential equations',
  'differential games',
  'differential geometry',
  'digital libraries',
  'digital multimedia',
  'discrete mathematics',
  'display devices',
  'distributed computing',
  'drug addiction',
  'drug delivery',
  'drug discovery',
  'dynamic economic models',
  'dynamical systems',
  'e-business',
  'e-commerce',
  'e-health',
  'e-learning',
  'e-learning',
  'ecology',
  'econometrics',
  'economics',
  'ecosystems',
  'education',
  'electric power',
  'electrical engineering',
  'electrochemistry',
  'electromagnetism',
  'electronic materials',
  'electronics',
  'electrostatics',
  'embedded systems',
  'embryology',
  'emergency medicine',
  'emerging technologies',
  'endocrinology',
  'energy production',
  'entertainment',
  'entomology',
  'environmental biology',
  'environmental chemistry',
  'environmental engineering',
  'environmental geotechnology',
  'environmental pollution',
  'environmental science',
  'epidemiology',
  'epigenetics',
  'ergodic theory',
  'estimation',
  'estimation theory',
  'ethology',
  'evolutionary biology',
  'evolutionary computation',
  'evolutionary computing',
  'evolutionary dynamics',
  'exoplanets',
  'experimental designs',
  'extragalactic astronomy',
  'extremal combinatorics',
  'family practice',
  'femtochemistry',
  'fiber optics',
  'field theory',
  'fixed parameter tractability',
  'flashtalks',
  'flavor chemistry',
  'flow chemistry',
  'fluid dynamics',
  'food chemistry',
  'food production',
  'formal languages',
  'foundations of computer science',
  'foundations of quantum physics',
  'functional analysis',
  'fuzzy systems',
  'galactic astronomy',
  'game theory',
  'gaming',
  'gamma rays',
  'gastroenterology',
  'gender and sexuality studies',
  'general biology',
  'general finance',
  'general mathematics',
  'general relativity',
  'general topology',
  'genetic programming',
  'genetics',
  'genomics',
  'geochemistry',
  'geochronology',
  'geodesy',
  'geography',
  'geology',
  'geomagnetics',
  'geometric group theory',
  'geometric topology',
  'geometry',
  'geomicrobiology',
  'geomorphology',
  'geophysics',
  'geostatistics',
  'geriatrics',
  'glaciology',
  'graph theory',
  'graphene',
  'graphics',
  'green chemistry',
  'green computing',
  'grid computing',
  'group theory',
  'growth and synthesis',
  'gynecology',
  'habitable zone',
  'haematology',
  'hair transplantation',
  'hardware architecture',
  'hazardous materials',
  'health care',
  'hepatology',
  'herpetology',
  'high performance computing',
  'histochemistry',
  'histology',
  'history',
  'history of cosmic ray research',
  'human resource management',
  'human-computer interaction',
  'human-computer interaction',
  'hydraulics',
  'hydrogenation chemistry',
  'hydrogeology',
  'hydrology',
  'hypertension',
  'ichthyology',
  'image processing',
  'immunity',
  'immunochemistry',
  'immunology',
  'industrial chemistry',
  'industrial microbiology',
  'industrial relations',
  'industry',
  'infectious diseases',
  'inflammation',
  'information retrieval',
  'information systems',
  'information technology',
  'information theory',
  'inorganic chemistry',
  'integrated optics',
  'integrative biology',
  'intelligent systems',
  'internal medicine',
  'international studies',
  'internet architecture',
  'ion channels',
  'ionization physics',
  'k-theory and homology',
  'kernelization',
  'knowledge discovery',
  'knowledge engineering',
  'knowledge management',
  'knowledge representation',
  'language',
  'laser physics',
  'lasers',
  'lattice gases',
  'law',
  'legal management',
  'library science',
  'life sciences',
  'light squeezing',
  'light storage',
  'light-matter interaction',
  'limit theory',
  'limnology',
  'linear algebra',
  'linear models',
  'linguistics',
  'literature',
  'logic',
  'loop quantum gravity',
  'low-dimensional systems',
  'm-theory',
  'machine learning',
  'magnetic materials',
  'malaria',
  'mammalogy',
  'mammography',
  'mantle plumes',
  'many body systems',
  'marine biology',
  'marine chemistry',
  'marine geology',
  'marine microbes',
  'marketing',
  'mars',
  'mass spectroscopy',
  'materials chemistry',
  'materials engineering',
  'materials physics',
  'materials science',
  'mathematcics',
  'mathematical biology',
  'mathematical chemistry',
  'mathematical physics',
  'mathematical software',
  'mathematical statistics',
  'mechanical oscillators',
  'mechanochemistry',
  'mechatronics',
  'media studies',
  'medical physics',
  'metabolic diseases',
  'metabolic diseases',
  'metabolic regulation',
  'metabolism',
  'metallurgy',
  'meteorology',
  'methodology',
  'methods and protocols',
  'metric geometry',
  'metrology',
  'microbial stresses',
  'microbiology',
  'micropaleontology',
  'microscopy',
  'microtechnology',
  'mineral processing',
  'mineralogy',
  'mitochondrial metabolism',
  'mobile computing',
  'modeling and control systems',
  'modeling and simulation',
  'molecular biology',
  'molecular imaging',
  'molecular mechanics',
  'molecular modeling',
  'molecular physics',
  'multi-agent systems',
  'multiagent systems',
  'multimedia',
  'multivariate analysis',
  'mycology',
  'nanobiology',
  'nanomaterials',
  'nanomechanics',
  'nanomedicine',
  'nanophotonics',
  'nanophysics',
  'nanoscience',
  'nanotechnology',
  'natural disasters',
  'natural language processing',
  'naturalproduct chemistry',
  'nephrology',
  'network science',
  'network security',
  'networks security',
  'neural networks',
  'neurobiology',
  'neurochemistry',
  'neurofeedback',
  'neurogenesis',
  'neuroimaging',
  'neurology',
  'neuropeptides',
  'neuroscience',
  'neurosurgery',
  'neurotoxicology',
  'neutrons',
  'nmr',
  'non-locality',
  'nonlinear optics',
  'nonlinear science',
  'nonparametric inference',
  'nuclear chemistry',
  'nuclear energynuclear technology',
  'nuclear magnetic resonance imaging',
  'nuclear medicine',
  'nuclear physics',
  'nuclear structure and reaction mechanism',
  'number theory',
  'numerical analysis',
  'numerical simulation',
  'nursing',
  'nutrition',
  'nutrition science',
  'obstetrics',
  'occupational health',
  'occupational safety',
  'oceanography',
  'oenology',
  'official statistics',
  'oligonucleotides',
  'oncology',
  'open quantum systems',
  'open science',
  'open source',
  'operating systems',
  'operational research',
  'operations research',
  'operator algebras',
  'operator theory',
  'ophthalmology',
  'optical fibres',
  'optical lattices',
  'optics',
  'optimal control',
  'optimization',
  'optimization and control',
  'optoelectronics',
  'organic chemistry',
  'organometallic chemistry',
  'ornithology',
  'paleoclimatology',
  'paleontology',
  'palynology',
  'parallel computing',
  'parametric down-conversion',
  'parametric inference',
  'parasitology',
  'particle physics',
  'pathobiology',
  'pathology',
  'pattern formation',
  'pattern recognition',
  'pattern recognition',
  'pediatrics',
  'peptides',
  'performing arts',
  'pervasive computing',
  'petrochemistry',
  'petrology',
  'pharmaceutical chemistry',
  'pharmacology',
  'philosophical',
  'philosophy',
  'photobiology',
  'photochemistry',
  'photon science',
  'photonics',
  'physical chemistry',
  'physicochemical',
  'physiology',
  'phytochemistry',
  'phytopathology',
  'planetary science',
  'plant biology',
  'plant science',
  'plasma',
  'plasma physics',
  'plastic processing',
  'plate tectonics',
  'pneumococci',
  'political science',
  'polymer chemistry',
  'polymers',
  'population biology',
  'population ecology',
  'population genetics',
  'portfolio management',
  'power engineering',
  'predictive analytics',
  'preventive medicine',
  'pricing of securities',
  'privacy',
  'probability',
  'programming',
  'programming language theory',
  'programming languages',
  'prostate cancer',
  'proteins',
  'psychiatrists',
  'psychiatry',
  'psychobiology',
  'psychology',
  'psychophysiology',
  'public administration',
  'public health',
  'pulmonology',
  'quality control',
  'quantitative finance',
  'quantum algebra',
  'quantum algorithms',
  'quantum biology',
  'quantum channels',
  'quantum chromodynamics',
  'quantum computing',
  'quantum cryptography',
  'quantum devices',
  'quantum discord',
  'quantum electrodynamics',
  'quantum electronics',
  'quantum error correction',
  'quantum field theory',
  'quantum hall effect',
  'quantum information',
  'quantum information processing',
  'quantum magnetism',
  'quantum measurement',
  'quantum memory',
  'quantum metrology',
  'quantum networks',
  'quantum optics',
  'quantum physics',
  'quantum simulations',
  'queues',
  'radiation protection',
  'radiation therapy',
  'radiobiology',
  'radiochemistry',
  'radiology',
  'railways',
  'randomforests',
  'regression',
  'reliability',
  'reliability theory',
  'religion',
  'renewable energy',
  'representation theory',
  'resting state',
  'rheumatology',
  'rings and algebras',
  'risk management',
  'robotics',
  'safety',
  'salford predictive modeler',
  'salford systems',
  'scanning probe microscopy',
  'schroedinger equation',
  'science policy',
  'security',
  'sedimentology',
  'seismology',
  'self-organisation',
  'self-organizing systems',
  'semiconductors',
  'sensor networks',
  'sequential analysis',
  'short-presentations',
  'signal processing',
  'signalling networks',
  'sleep medicine',
  'social and information networks',
  'social networks',
  'sociobiology',
  'sociology',
  'software',
  'software engineering',
  'soil science',
  'solar physics',
  'solar power',
  'solid earth science',
  'solid state',
  'solid state physics',
  'solitons',
  'sonochemistry',
  'sonography',
  'sound',
  'space exploration',
  'space probes',
  'spaceflight',
  'special relativity',
  'spectral theory',
  'spectroscopy',
  'staitstical genetics',
  'standard model',
  'statistical computation',
  'statistical computing',
  'statistical finance',
  'statistical genetics',
  'statistical inference',
  'statistical mechanics',
  'statistical physics',
  'statistics',
  'stellar astronomy',
  'stem cells',
  'stochastic PDE',
  'stochastic analysis',
  'stochastic calculus',
  'stochastic dynamics',
  'stochastic finance',
  'stochastic processes',
  'stratigraphy',
  'string theory',
  'structural biology',
  'structural studies',
  'supernova',
  'supersymmetry',
  'supramolecular chemistry',
  'surface chemistry',
  'surgery',
  'survey sampling',
  'survival analysis',
  'sustainability',
  'sustainable development',
  'symbolic computation',
  'symplectic geometry',
  'synchrotron radiation',
  'synthetic biology',
  'synthetic chemistry',
  'synthetic materials',
  'system biology',
  'systems and control',
  'systems biology',
  'systems biology',
  'systems security',
  'teaching chemistry',
  'teaching mathematics',
  'teaching physics',
  'tectonics',
  'testing of hypotheses',
  'text mining',
  'theoretical computer science',
  'theoretical physics',
  'thermochemistry',
  'thermodynamics',
  'time series',
  'tomography',
  'topological quantum states',
  'topological quantum systems',
  'topology',
  'tourism',
  'toxicology',
  'trading and market microstructure',
  'transit light curves',
  'transplantation',
  'transportation',
  'trauma care',
  'treenet',
  'trichology',
  'tumor microenvironment',
  'ubiquitin',
  'ubiquitous computing',
  'ultra-high energy',
  'ultracold atoms',
  'ultrafast phenomena',
  'ultrashort pulses',
  'urology',
  'user interfaces',
  'virology',
  'virtual reality',
  'visual arts',
  'volcanology',
  'waste management',
  'water treatment',
  'wave optics',
  'web conferencing',
  'web servers',
  'web services',
  'wind energy',
  'windpower',
  'wireless',
  'zoology',
];
